name: base
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - pip
  - ipython
  - jupyterlab
  - numpy
  - pandas
  - requests
  - pydantic
  - pip:
      - mcp  # Replace with actual SDK name or source
      - mcp[cli]
      - openai
